---
version: "3"
services:
  ipfs:
    image: js-ipfs:latest
    container_name: ipfs
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config/ipfs:/data/ipfs
    ports:
      - 5002:5002 # HTTP API
      - 9090:9090 # Gateway
    restart: unless-stopped
